### ISSUE TITLE
Allow for partial charge method setting specification

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/feflow#47]
It is convenient for users to be able to specify the partial charge generation method, especially if other toolkits different from ambertools (such as OpenEye) are available. Using the [`OpenFFPartialChargeSettings` model from `openfe`](https://github.com/OpenFreeEnergy/openfe/blob/48dcbb26e894c98566731b65224465c25a3c0fe4/openfe/protocols/openmm_utils/omm_settings.py#L75) seems like the way to go.

**Comment by ijpulidos** [comment]
This is related to the comment in https://github.com/choderalab/feflow/pull/38#issuecomment-2147979007 @dotsdl

**Comment by dotsdl** [comment]
Thanks @ijpulidos, I will take this one on!

**Comment by dotsdl** [comment]
Actually, @ianmkenney: is this something you would be willing to hit?

**Comment by IAlibay** [comment]
Just a brief outline of what needs doing.

1. Re-create this (I can't remmber if we aligned on the `off_small_mols` dictionary yet): https://github.com/OpenFreeEnergy/openfe/blob/48dcbb26e894c98566731b65224465c25a3c0fe4/openfe/protocols/openmm_rfe/equil_rfe_methods.py#L621-L647
2. Change this loop: https://github.com/choderalab/feflow/blob/e7fb6f67bd198c39a0abaa41bd700da778dea8b3/feflow/protocols/nonequilibrium_cycling.py#L197-L210
 a. Instead it should be a call to the charge assignment method and then after that a loop over molecules passing them to `system_generator.create_system`

**Comment by ijpulidos** [comment]
Solved by #49
